default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: leve_casa_hub_develop

test:
  <<: *default
  database: leve_casa_hub_test

production:
  primary: &primary_production
    <<: *default
    database: leve_casa_production
    username: leve_casa
    password: <%= ENV["LEVE_CASA_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: leve_casa_hub_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: leve_casa_hub_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: leve_casa_hub_production_cable
    migrations_paths: db/cable_migrate
